# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Redis: '@snc_redis.default'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\Country\Set:
        arguments:
            $setter: '@App\Service\Statistic\Country\Set\DefaultImpl'

    App\Controller\Country\Get:
        arguments:
            $getter: '@App\Service\Statistic\Country\Get\FromRedisCache'

    App\Command\UpdateCache:
        arguments:
            $redisAccessor: '@App\Service\Statistic\Country\Get\RedisAccessor'

    App\Service\Statistic\Country\Get\FromRedisCache:
        arguments:
            $nullAccessor: '@App\Service\Statistic\Country\Get\NullAccessor'

    App\Service\Statistic\Country\Set\DefaultImpl:
        arguments:
            $builder: '@App\Service\Statistic\Country\Builder\ValidationDecorator'

    App\Service\Statistic\Country\Builder\FromRequest: ~

    App\Service\Statistic\Country\Builder\ValidationDecorator:
        arguments:
            $decorated: '@App\Service\Statistic\Country\Builder\FromRequest'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
